# Generated by Django 5.0.6 on 2024-05-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorvalue',
            name='value2',
            field=models.FloatField(default=12, verbose_name='Значение1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='value3',
            field=models.FloatField(default=121, verbose_name='Значение2'),
            preserve_default=False,
        ),
    ]
