# Generated by Django 5.0.6 on 2024-05-29 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_indicatorvalue_value2_indicatorvalue_value3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('current_ratio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quick_ratio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('absolute_ratio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chart', models.TextField()),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
