# Generated by Django 5.0.6 on 2024-05-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='absolute_ratio',
        ),
        migrations.RemoveField(
            model_name='report',
            name='current_ratio',
        ),
        migrations.RemoveField(
            model_name='report',
            name='quick_ratio',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_date',
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='report_data',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
